auth {
    pam {
        enabled = true
        module = hyprlock
    }
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint to unlock
        present_message = Scanning...
        retry_delay = 250
    }
}

background {
    color = rgba(000000ff)
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 2
    dots_center = true
    placeholder_text = <i>Password or fingerprint</i>
    position = 0, -20
    halign = center
    valign = center
}
